### PR TITLE
POSHI-473 Add validation for double quotes for multiline literal string

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Please see: https://issues.liferay.com/browse/POSHI-473

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
Sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/130297

**Comment by kenjiheigel** [comment]
ci:close

**Pull request closed without merging**
