### PR TITLE
POSHI-575 Support Object in ListUtil

### PR DESCRIPTION
**Pull request by epark18**
https://liferay.atlassian.net/browse/POSHI-575

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by bronsonsoda** [comment]
LGTM

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:stop

**Comment by CalumR23** [comment]
Resent here:
https://github.com/kenjiheigel/liferay-portal/pull/1431

**Pull request closed without merging**
