### PR TITLE
LRQA-67750

### PR DESCRIPTION
**Pull request by CalumR23**
[LRQA-67653](https://issues.liferay.com/browse/LRQA-67653)

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:forward

**Comment by CalumR23** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by CalumR23** [comment]
ci:forward

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:forward

**Pull request closed without merging**
